const ActionType = {
    GET_USER_ACTIVITY_REQUEST: "GET_USER_ACTIVITY_REQUEST",
    GET_USER_ACTIVITY_SUCCESS: "GET_USER_ACTIVITY_SUCCESS",
    GET_USER_ACTIVITY_ERROR: "GET_USER_ACTIVITY_ERROR",
    ADD_NEW_USER_ACTIVITY_SUCCESS: "ADD_NEW_USER_ACTIVITY_SUCCESS",
    DELETE_USER_ACTIVITY: "DELETE_USER_ACTIVITY",
    CHANGE_USER_ACTIVITY: "CHANGE_USER_ACTIVITY"
};

export default ActionType;
